# Job Search Agent Configuration

user_profile:
  name: "Hamza Asif"
  title: "React js Developer | AI Student"
  email: "hamza.asif0087@gmail.com"
  phone: "+921-9519624"  # <- Replace with your real phone number
  location: "Lahore, Pakistan"
  experience: "1+ years (Internships & Projects)"
  education:
    - degree: "BS (Hons)"
      field: "Artificial Intelligence"
      institution: "University of Management and Technology (UMT)"
      year: 2026
  skills:
    - "React.js"
    - "Next.js"
    - "Redux Toolkit"
    - "Express.js"
    - "Tailwind CSS"
    - "JavaScript"
    - "Python"
    - "Flask"
    - "Machine Learning"
    - "UI/UX Design"
    - "Git & GitHub"
  resume_path: "C:/Users/MADIHA/Desktop/Hamza_Asif_Resume_Updated-1.pdf"  # Ensure this path is correct
  portfolio_url: "https://hamzaasif043.github.io/Porfolio/"
  github_url: "https://github.com/HaMZAAsif043"
  linkedin_url: "https://linkedin.com/in/hamzaasif043"

job_search:
  job_types:
    - "Full-time"
    - "Contract"
    - "Freelance"
  experience_level:
    - "Junior-level"
    - "Mid-level"
    - "Internship"  # Optional: keep if you still want to consider internships too
  remote: true
  locations:
    - "Lahore, PK"
    - "Sahiwal, PK"
    - "Karachi, PK"
    - "Sahiwal, PK"
    - "Pakistan, PK"
    - "Remote"
  salary_range:
    min: 500
    max: 2500
    currency: "USD"
  keywords:
    - "React Developer"
    - "Nextjs Developer"
    - "MERN Stack Developer"
    - "Full Stack Developer"
    - "Front-End Developer"
    - "Junior Web Developer"
    - "AI Intern"
  exclude_keywords:
    - "PHP"
    - "WordPress"

platforms:
  linkedin:
    enabled: true
    show_browser: true
    credentials:
      username: "hamza.asif0087@gmail.com"
      password: "fH2iqR96E.fX_8v"
    search_criteria:
      post_days: 7
      location_distance: 25

  indeed:
    enabled: false
    show_browser: true
    credentials:
      username: ""
      password: ""
    search_criteria:
      post_days: 14
      location_distance: 50

  upwork:
    enabled: false
    show_browser: true
    credentials:
      username: "hamza.asif0087@gmail.com"
      password: "Thyroxin@43"
    search_criteria:
      hourly_rate:
        min: 10
        max: 30
      duration: "Less than 1 month"

  fiverr:
    enabled: false
    show_browser: true
    credentials:
      username: "your_username"
      password: "your_password"
    search_criteria:
      gig_categories:
        - "Programming & Tech"
        - "Digital Marketing"
      price_range:
        min: 50
        max: 500

application:
  auto_apply: false
  cover_letter_template: "templates/cover_letter.jinja"
  daily_application_limit: 10

notifications:
  email:
    enabled: true
    address: "hamza.asif0087@gmail.com"
  desktop:
    enabled: true

scheduler:
  enabled: true
  frequency: "daily"
  time: "09:00"
